package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Test2'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Test2")) {
    expectSteps {
        gradle {
            tasks = "test"
            buildFile = "build.gradle"
        }
    }
    steps {
        insert(0) {
            script {
                name = "asdf"
                scriptContent = """
                    set -x
                    date
                    echo "hello"
                """.trimIndent()
                dockerImage = "node:14.17"
            }
        }
        items.removeAt(1)
    }
}
